---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
spec:
  replicas: 1
  strategy: { type: Recreate }
  template:
    spec:
      containers:
      - name: operator
        image: postgres-operator
        env:
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RADONDB_DEBUG
          value: "true"
        - name: RELATED_IMAGE_POSTGRES_13
          value: "docker.io/radondb/radondb-postgres:centos8-13.5-1"
        - name: RELATED_IMAGE_POSTGRES_13_GIS_3.1
          value: "docker.io/radondb/radondb-postgres-gis:centos8-13.5-3.1-1"
        - name: RELATED_IMAGE_POSTGRES_14
          value: "docker.io/radondb/radondb-postgres:centos8-14.1-1"
        - name: RELATED_IMAGE_POSTGRES_14_GIS_3.1
          value: "docker.io/radondb/radondb-postgres-gis:centos8-14.1-3.1-1"
        - name: RELATED_IMAGE_PGADMIN
          value: "docker.io/radondb/radondb-pgadmin4:centos8-4.30-0"
        - name: RELATED_IMAGE_PGBACKREST
          value: "docker.io/radondb/radondb-pgbackrest:centos8-2.36-1"
        - name: RELATED_IMAGE_PGBOUNCER
          value: "docker.io/radondb/radondb-pgbouncer:centos8-1.16-1"
        - name: RELATED_IMAGE_PGEXPORTER
          value: "docker.io/radondb/radondb-postgres-exporter:ubi8-5.1.0-0"
        - name: RELATED_IMAGE_PGUPGRADE
          value: "docker.io/radondb/radondb-upgrade:ubi8-5.1.0-0"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: pgo
