apiVersion: postgres-operator.radondb.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: docker.io/radondb/radondb-postgres:centos8-14.1-1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteMany"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: docker.io/radondb/radondb-pgbackrest:centos8-2.36-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 1Gi
      - name: repo2
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 1Gi
  proxy:
    pgBouncer:
      image: docker.io/radondb/radondb-pgbouncer:centos8-1.16-1
