---
# Annotate the cluster with the timestamp at which PostgreSQL last started.
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      PRIMARY=$(
        kubectl get pod --namespace "${NAMESPACE}" \
          --output name --selector '
            postgres-operator.radondb.com/cluster=original,
            postgres-operator.radondb.com/role=master'
      )
      START=$(
        kubectl exec --namespace "${NAMESPACE}" "${PRIMARY}" \
          -- psql -qAt --command 'SELECT pg_postmaster_start_time()'
      )
      kubectl annotate --namespace "${NAMESPACE}" postgrescluster/original \
        "testing/start-before=${START}"
