---
apiVersion: postgres-operator.radondb.com/v1beta1
kind: PostgresCluster
metadata:
  name: switchover
status:
  instances:
    - name: "00"
      replicas: 2
      readyReplicas: 2
      updatedReplicas: 2
