namespace: postgres-operator

commonLabels:
  postgres-operator.radondb.com/control-plane: postgres-operator

bases:
- ../crd
- ../rbac/namespace
- ../manager

patches:
- manager-target.yaml

images:
- name: postgres-operator
  newName: docker.io/radondb/postgres-operator
  newTag: ubi8-5.1.0-0
