apiVersion: postgres-operator.radondb.com/v1beta1
kind: PostgresCluster
metadata:
  name: scaledown1
status:
  instances:
    - name: instance1
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    postgres-operator.radondb.com/cluster: scaledown1
    postgres-operator.radondb.com/instance-set: instance1
    postgres-operator.radondb.com/role: master
status:
  phase: Running
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    postgres-operator.radondb.com/cluster: scaledown1
    postgres-operator.radondb.com/instance-set: instance1
    postgres-operator.radondb.com/role: replica
status:
  phase: Running
