# Manual backup job should have pushed to repo2
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    postgres-operator.radondb.com/cluster: init-pgbackrest
    postgres-operator.radondb.com/pgbackrest-backup: manual
    postgres-operator.radondb.com/pgbackrest-repo: repo2
status:
  succeeded: 1
